padding-x = 10

# padding-y = [10, 10]

# Option as Alt
#
# This config only works on MacOS.
# Possible choices: 'both', 'left' and 'right'.
#
# Example:
# option-as-alt = 'left'

use-fork = false

[editor]
program = "nvim"

[fonts]
size = 18

[navigation]
mode = "toptab"

[shell]
program = "/opt/homebrew/bin/nu"
args = ["--login"]

[platform.linux.shell]
program = "/bin/nu"
args = ["--login"]

[platform.macos.shell]
program = "/opt/homebrew/bin/nu"
args = ["--login"]

[platform.windows.shell]
program = "nu"
args = ["--login"]
